namespace MarketBlocks.Infrastructure.Tradier;

/// <summary>
/// Static utility to deterministically map Tradier's int Order IDs to Guid and back.
/// Tradier uses integer order IDs, but our broker-agnostic interface uses Guids.
/// </summary>
public static class TradierIdHelper
{
    /// <summary>
    /// Converts a Tradier integer order ID to a Guid.
    /// The integer is embedded in the first 4 bytes of the Guid.
    /// </summary>
    /// <param name="tradierId">The Tradier order ID (integer).</param>
    /// <returns>A deterministic Guid representation.</returns>
    public static Guid ToGuid(int tradierId)
    {
        // Create a 16-byte array (size of Guid)
        var bytes = new byte[16];
        
        // Embed the int in the first 4 bytes (little-endian)
        BitConverter.TryWriteBytes(bytes.AsSpan(0, 4), tradierId);
        
        // Add a marker pattern in bytes 4-7 to identify Tradier-generated Guids
        // Using "TRDR" as ASCII: 0x54, 0x52, 0x44, 0x52
        bytes[4] = 0x54; // T
        bytes[5] = 0x52; // R
        bytes[6] = 0x44; // D
        bytes[7] = 0x52; // R
        
        // Remaining bytes stay as zeros
        
        return new Guid(bytes);
    }
    
    /// <summary>
    /// Extracts the Tradier integer order ID from a Guid.
    /// </summary>
    /// <param name="guid">The Guid to convert back.</param>
    /// <returns>The original Tradier order ID.</returns>
    public static int ToTradierId(Guid guid)
    {
        var bytes = guid.ToByteArray();
        return BitConverter.ToInt32(bytes, 0);
    }
    
    /// <summary>
    /// Checks if a Guid was generated by this helper (has the Tradier marker).
    /// </summary>
    /// <param name="guid">The Guid to check.</param>
    /// <returns>True if this Guid was generated from a Tradier ID.</returns>
    public static bool IsTradierGuid(Guid guid)
    {
        var bytes = guid.ToByteArray();
        return bytes[4] == 0x54 && // T
               bytes[5] == 0x52 && // R
               bytes[6] == 0x44 && // D
               bytes[7] == 0x52;   // R
    }
}
